apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: go-demo-app
spec:
  image: "australia-southeast2-docker.pkg.dev/${GCP_PROJECT}/cmek-container-images/dev/go-demo-app"
  interval: 1m0s
  # secretRef:
  #   name: regcred
  provider: gcp
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: go-demo-app
spec:
  imageRepositoryRef:
    name: go-demo-app
  filterTags:
    pattern: '[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
