apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pod-labeler
spec:
  interval: 1m0s
  releaseName: pod-labeler
  chart:
    spec:
      chart: ./infra/pod-labeler
      sourceRef:
        kind: GitRepository
        name: pod-labeler
        namespace: flux-system
  values:
    image:
      repository: andreistefanciprian/pod-labeler-k8s-webhook # {"$imagepolicy": "flux-system:pod-labeler"}
      tag: ed366f9f68615f97d09398a126d8d69edc9cc6cb # {"$imagepolicy": "flux-system:pod-labeler:tag"}