apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: egress-gateway
spec:
  interval: 1m0s
  releaseName: egress-gateway
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    service:
      # Egress gateways do not need an external LoadBalancer IP
      type: ClusterIP
  
