apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
  namespace: flux-system
data:
  GCP_PROJECT: arctic-column-480422-n4
  CLUSTER_DOMAIN: demo.example.com
  GCP_REGION: australia-southeast1
