---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  type: oci
  url: oci://ghcr.io/controlplaneio-fluxcd/charts
  interval: 12h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: flux-operator
      version: 0.38.1
      sourceRef:
        kind: HelmRepository
        name: flux-operator
      interval: 12h
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    serviceMonitor:
      create: true
      interval: 60s
      scrapeTimeout: 30s
