releases:
  - name: flux-operator
    namespace: flux-system
    chart: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
    version: 0.38.1
    createNamespace: true
    values:
      - serviceMonitor:
          create: false
          interval: 60s
          scrapeTimeout: 30s

  # Install FluxInstance after the operator
  - name: flux-instance
    namespace: flux-system
    chart: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-instance
    version: 0.38.1
    needs:
      - flux-system/flux-operator
    values:
      - values-flux-instance.yaml

