apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: go-demo-app-tls
  namespace: go-demo-app
spec:
  secretName: go-demo-app-tls
  dnsNames:
  - "go-demo-app.${CLUSTER_DOMAIN}"
  issuerRef:
    group: cas-issuer.jetstack.io
    kind: GoogleCASClusterIssuer
    name: googlecasclusterissuer
