apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: go-demo-app
spec:
  interval: 1m0s
  releaseName: go-demo-app
  chart:
    spec:
      chart: go-demo-app
      sourceRef:
        kind: HelmRepository
        name: go-demo-app
        namespace: flux-system
  values:
    image:
      repository: australia-southeast2-docker.pkg.dev/esoteric-code-394122/cmek-container-images/dev/go-demo-app
      tag: bd2e98f9d5ffcfc54d0a9d84a44913f370cb626e-22 # {"$imagepolicy": "flux-system:go-demo-app:tag"}
