apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: go-demo-app
spec:
  interval: 1m0s
  releaseName: go-demo-app
  chart:
    spec:
      chart: ./infra/go-demo-app
      sourceRef:
        kind: GitRepository
        name: go-demo-app
        namespace: flux-system
  values:
    image:
      repository: australia-southeast2-docker.pkg.dev/dazzling-tiger-384923/cmek-container-images/dev/go-demo-app # {"$imagepolicy": "flux-system:go-demo-app"}
      tag: "0.1.4" # {"$imagepolicy": "flux-system:go-demo-app:tag"}