apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: go-demo-app
spec:
  interval: 1m0s
  releaseName: go-demo-app
  chart:
    spec:
      chart: go-demo-app
      version: v0.1.0-60 # {"$imagepolicy": "flux-system:go-demo-app-chart:tag"}
      sourceRef:
        kind: HelmRepository
        name: go-demo-app
        namespace: flux-system
  values:
    image:
      repository: "australia-southeast2-docker.pkg.dev/${GCP_PROJECT}/cmek-container-images/dev/go-demo-app"
      tag: d83d107b363e12b174561141be7a731a40384ee4-32 # {"$imagepolicy": "flux-system:go-demo-app:tag"}
