apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
spec:
  interval: 1m0s
  releaseName: istiod
  chart:
    spec:
      chart: istiod
      version: '1.21.0'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  dependsOn:
    - name: istio
  values:
    #  enables access logging for the entire mesh
    meshConfig:
      accessLogFile: /dev/stdout
      accessLogEncoding: JSON
      outboundTrafficPolicy:
        mode: REGISTRY_ONLY
    pilot:
      env:
        EXTERNAL_ISTIOD: false
        PILOT_ENABLE_GATEWAY_API: true
  
