apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
spec:
  interval: 1m0s
  releaseName: istiod
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    #  enables access logging for the entire mesh
    meshConfig:
      accessLogFile: /dev/stdout
      accessLogEncoding: JSON
  
