apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio
spec:
  interval: 1m0s
  releaseName: istio
  chart:
    spec:
      chart: base
      version: '1.17.5'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
  
