apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-gateway
spec:
  interval: 1m0s
  releaseName: ingress-gateway
  chart:
    spec:
      chart: gateway
      version: '1.21.0'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  dependsOn:
    - name: istio
      namespace: istio-system
    - name: istiod
      namespace: istio-system
  values:
  
