apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pod-restarter
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infra/pod-restarter
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system