# https://github.com/andreistefanciprian/terraform-kubernetes-gke-cluster/blob/main/secrets/main.tf
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-secrets
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/esoteric-code-394122/secrets/my-secret/versions/latest"
        path: "good1.txt"
      - resourceName: "projects/esoteric-code-394122/secrets/my-secret/versions/latest"
        path: "good2.txt"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mypod
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: secrets-reader@esoteric-code-394122.iam.gserviceaccount.com
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: default
spec:
  serviceAccountName: mypod
  containers:
  - name: busybox
    image: registry.k8s.io/e2e-test-images/busybox:1.29
    command:
    - "/bin/sleep"
    - "10000"
    volumeMounts:
      - mountPath: "/var/secrets"
        name: mysecret
  volumes:
  - name: mysecret
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "app-secrets"
# kubectl exec -ti mypod cat /var/secrets/good2.txt