apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: priorityclass-webhook
spec:
  interval: 1m0s
  releaseName: priorityclass-webhook
  chart:
    spec:
      chart: ./infra/priorityclass-webhook
      sourceRef:
        kind: GitRepository
        name: priorityclass-webhook
        namespace: flux-system
  values:
    image:
      repository: andreistefanciprian/k8s-priorityclass-webhook
      tag: main-7325e4c5-1739672425 # {"$imagepolicy": "flux-system:priorityclass-webhook:tag"}
