apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: descheduler
spec:
  interval: 1m0s
  releaseName: descheduler
  chart:
    spec:
      chart: descheduler
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
  values:
    kind: Deployment
    deschedulerPolicy:
      strategies:
        RemovePodsHavingTooManyRestarts:
          params:
            podsHavingTooManyRestarts:
              podRestartThreshold: 5
              includingInitContainers: true
        RemoveFailedPods:
          enabled: true
          params:
            reasons:
              - "CrashLoopBackOff"
              - "ImagePullBackOff"
              - "FailedCreatePodSandBox"
            includingInitContainers: true
            # excludeOwnerKinds:
            # - "DaemonSet"
            minPodLifetimeSeconds: 60
    priorityClassName: high-priority-nonpreempting
    service:
      enabled: true
    serviceMonitor:
      enabled: true
