apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: secrets-store-csi-driver-provider-gcp
spec:
  interval: 10m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp.git