apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: go-demo-app-alerts
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: flux
spec:
  groups:
  - name: go-demo-app.rules
    interval: 30s
    rules:
    - alert: GoDemoAppHelmReleaseNotReady
      expr: gotk_resource_info{customresource_kind="HelmRelease",exported_namespace="go-demo-app",name="go-demo-app",ready="False"} == 1
      for: 1m
      labels:
        severity: warning
        component: go-demo-app
        namespace: go-demo-app
      annotations:
        summary: "Go Demo App HelmRelease is not ready"
        description: "The HelmRelease {{ $labels.name }} in namespace {{ $labels.exported_namespace }} has been in a not-ready state for more than 5 minutes."
        runbook_url: "https://fluxcd.io/docs/components/helm/helmreleases/"
    
    - alert: GoDemoAppHelmReleaseSuspended
      expr: gotk_resource_info{customresource_kind="HelmRelease",exported_namespace="go-demo-app",name="go-demo-app",suspended="true"} == 1
      for: 1m
      labels:
        severity: info
        component: go-demo-app
        namespace: go-demo-app
      annotations:
        summary: "Go Demo App HelmRelease is suspended"
        description: "The HelmRelease {{ $labels.name }} in namespace {{ $labels.exported_namespace }} is currently suspended."
