# This file defines a SecretProviderClass for the Slack webhook URL
# to be used by the Alertmanager in the monitoring namespace.
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: slack-webhook
  namespace: monitoring
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/${GCP_PROJECT}/secrets/slack-webhook/versions/latest"
        path: "url"
  secretObjects:
  - secretName: slack-webhook
    type: Opaque
    data:
    - objectName: "url"
      key: "url"
