apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: instavote-redis
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./deploy/redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote
  targetNamespace: instavote
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: redis
      namespace: instavote
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: instavote-vote
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./deploy/vote
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote
  targetNamespace: instavote
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: vote
      namespace: instavote
  dependsOn:
    - name: instavote-redis
---
apiVersion: v1
kind: Namespace
metadata:
  name: instavote
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: instavote
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/andreistefanciprian/instavote.git