apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infra/istio
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system