apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: priorityclass-webhook
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infra/priorityclass-webhook
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager-cas-issuer-config
