apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secrets-store-csi-driver
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infra/secrets-store-csi-driver
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system