apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: watchlist-slack-bot
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: default
  prune: true
  sourceRef:
    kind: OCIRepository
    name: watchlist-slack-bot
  path: ./
  dependsOn:
    - name: watchlist-slack-bot-oci-repo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: watchlist-slack-bot-oci-repo
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infra/watchlist-slack-bot
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
  sourceRef:
    kind: GitRepository
    name: flux-system