apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: watchlist-slack-bot
  namespace: flux-system
spec:
  interval: 10m
  url: oci://australia-southeast2-docker.pkg.dev/liquid-verbena-425321-k7/manifests/watchlist-slack-bot
  ref:
    tag: latest
  provider: gcp
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: watchlist-slack-bot
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: default
  prune: true
  sourceRef:
    kind: OCIRepository
    name: watchlist-slack-bot
  path: ./