apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 1m0s
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.12.3
      sourceRef:
        kind: HelmRepository
        name: jetstack-charts
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    global:
      priorityClassName: high-priority-nonpreempting
    installCRDs: true
    # When this flag is enabled, secrets will be automatically removed when the certificate resource is deleted
    enableCertificateOwnerRef: true
