# https://fluxcd.io/flux/guides/cron-job-image-auth/#gcp-container-registry
# https://github.com/andreistefanciprian/terraform-kubernetes-gke-cluster/blob/main/artifact_registry/flux_image_policy.tf
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gcr-credentials-sync
  namespace: flux-system
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - create
  - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gcr-credentials-sync
  namespace: flux-system
subjects:
- kind: ServiceAccount
  name: gcr-credentials-sync
roleRef:
  kind: Role
  name: gcr-credentials-sync
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: "flux-gar-authenticator@${GCP_PROJECT}.iam.gserviceaccount.com"
  name: gcr-credentials-sync
  namespace: flux-system
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gcr-credentials-sync
  namespace: flux-system
spec:
  suspend: false
  schedule: "*/45 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: gcr-credentials-sync
          restartPolicy: Never
          volumes:
          - name: bash-script
            configMap:
              name: bash-script
              defaultMode: 0777
          containers:
          - image: google/cloud-sdk
            name: create-secret
            imagePullPolicy: IfNotPresent
            env:
            - name: SECRET_NAME
              value: regcred
            - name: GCR_REGISTRY
              value: "australia-southeast2-docker.pkg.dev/${GCP_PROJECT}/cmek-container-images/dev/go-demo-app"
            volumeMounts:
              - mountPath: /tmp
                name: bash-script
            command:
            - /bin/bash
            - -ce
            - |-
              ls /tmp/
              cat /tmp/create-secret.sh
              /tmp/create-secret.sh    
            securityContext:
              allowPrivilegeEscalation: false
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop: ["ALL"]
              runAsNonRoot: false