apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gateway-api-crds
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: gateway-api
    namespace: flux-system
  path: "./config/crd/standard"
  prune: true
  wait: true
