apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: priorityclass-webhook
  namespace: flux-system
spec:
  image: andreistefanciprian/k8s-priorityclass-webhook
  interval: 1m0s
  # secretRef:
  #   name: regcred
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: priorityclass-webhook
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: priorityclass-webhook
  filterTags:
    pattern: '[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc