name: Prod Auto-PR
on:
  create:
    branches: ['production']

permissions:
  pull-requests: write

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        run: |
          gh pr create --title "Push to prod" --body "Push new tag to prod GAR" --reviewer andreistefanciprian || gh pr edit --title "Push to prod" --body "Push new tag to prod GAR"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
