name: Prod Auto-PR
on:
  push:
    branches:
      - production

permissions:
  pull-requests: write

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        run: |
          gh pr create --title "Push to Prod GAR" --body "Push new container image or helm chart to Google Artifact Registry" --reviewer andreistefanciprian || gh pr edit --title "Push to Prod GAR" --body "Push new container image or helm chart to Google Artifact Registry"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
