name: Staging Auto-PR
on:
  create:
    branches: ['production']

permissions:
  pull-requests: write

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        run: |
          gh_pr_up() { gh pr create $* || gh pr edit $* }
          gh_pr_up --title "Push to prod" --body "Push new tag to prod GAR"